---
title: "Reaction Time"
author: "Benjamin Holding"
date: "10/02/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
} #function to see if package is installed. Will download if not, and then opens it.

packages <- c("data.table", "lubridate", "anytime", "dplyr", "ggplot2", "nlme", "tidyr", "nlme") #These are the extra packages needed to merge the CSV files
suppressPackageStartupMessages(ipak(packages))
```


```{r}

myoriginalwd <- getwd()
setwd("Slesi_reaction_time_renamed") #enter the location of the data here between quotation marks
file_list <- list.files()
L <- length(file_list) 

Q_list <- lapply(file_list, read.csv, header=T, sep=",", dec=".")

setwd(myoriginalwd)
RT.names <- read.csv("Reaction_time_file_names.csv", header = F)

names(Q_list) <- RT.names[,1]

final.list <- mapply(cbind, Q_list, "SampleID"=RT.names[,1], SIMPLIFY=F)

Questionnaires_KSS <- rbindlist(final.list, fill = T) #this is the complete data frame
Questionnaires_KSS$id <- as.character(Questionnaires_KSS$id)
Questionnaires_KSS$id[which(Questionnaires_KSS$id == "SI_106_2")] <- "SI_106"
Questionnaires_KSS$id[which(Questionnaires_KSS$id == "SI_106_3")] <- "SI_106"
Questionnaires_KSS$id[which(Questionnaires_KSS$id == "SI_106_4")] <- "SI_106"

Questionnaires_KSS$id <- as.numeric(gsub("[^0-9]","",Questionnaires_KSS$id))
colnames(Questionnaires_KSS)[1] <- "ID"

slesi.key <- read.csv("SleSI_Masterkey.csv")

Questionnaires_KSS_complete <- inner_join(Questionnaires_KSS, slesi.key)

Questionnaires_KSS_complete$SampleID <- gsub("RT_", "", Questionnaires_KSS_complete$SampleID)
Questionnaires_KSS_complete$SampleID <- gsub(".csv", "", Questionnaires_KSS_complete$SampleID)

KSS_Complete_TIDY <- Questionnaires_KSS_complete[c(-1,-2,-3)] %>% 
  separate(SampleID, into = c("ID", "time"), sep = "\\_")
                             
KSS_Complete_TIDY$time <- as.integer(KSS_Complete_TIDY$time)

KSS_Complete_TIDY <- KSS_Complete_TIDY[which(KSS_Complete_TIDY$reaction_time > 100 & KSS_Complete_TIDY$reaction_time < 4000),]

```

#multileveling the RT data
```{r}

model.ignore<-lm(reaction_time~time, data=KSS_Complete_TIDY)
summary(model.ignore)

model.1<-gls(reaction_time~1, data=KSS_Complete_TIDY, na.action=na.omit)
summary(model.1)

model.2<-lme(reaction_time~1, random=~1|ID, data=KSS_Complete_TIDY, na.action=na.omit)
anova(model.1,model.2) #model with random effects is significantly better
summary(model.2)

VarCorr(model.2)
10122.76/(10122.76+31280.16) #25% of variance can be attributed to variance in RT between individuals

# assessing the best time polynomial
model.3a<-lme(reaction_time~1, random=~1|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML")
model.3b<-lme(reaction_time~time, random=~1|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML")
model.3c<-lme(reaction_time~time+I(time^2), random=~1|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML")
model.3d<-lme(reaction_time~time+I(time^2)+I(time^3), random=~1|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML") 

anova(model.3a, model.3b, model.3c, model.3d) #the cubic model is the best

summary(model.3d)

# assessing the best random effects term
model.4a<-lme(reaction_time~time+I(time^2)+I(time^3), random=~1|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="REML") 

model.4b<-lme(reaction_time~time+I(time^2)+I(time^3), random=~time|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="REML") 

model.4c<-lme(reaction_time~time+I(time^2)+I(time^3), random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="REML") 

model.4d<-lme(reaction_time~time+I(time^2)+I(time^3), random=~time+I(time^2)+I(time^3)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="REML") #doesn't converge

anova(model.4a,model.4b,model.4c) #having random slopes for quadratic term for time is best

#checking model autocorrelation
model.5a<-lme(reaction_time~time+I(time^2)+I(time^3), random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="REML", correlation = corAR1()) 
anova(model.4c, model.5a) #there is significant autocorrelation - what do i do?

#determining heterosedasticity
model.5b<-lme(reaction_time~time+I(time^2)+I(time^3), random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="REML", weights = varExp(form = ~time)) 
anova(model.4c, model.5b) #there is also heteroscedasticity - what do i do?

#additing in variables can that explain intercept and slope variability
model.6a<-lme(reaction_time~time+I(time^2)+I(time^3), random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML") 
model.6b<-lme(reaction_time~time+I(time^2)+I(time^3)+SD, random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML") 

anova(model.6a,model.6b)#condition doesn't predict intercept, which is good because there should be no difference

model.6c <-lme(reaction_time~time*SD+I(time^2)+I(time^3), random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML") 

anova(model.6a,model.6c) #sleep deprivation explains variance in slope of time (linear)

model.6d <-lme(reaction_time~time*SD+I(time^2)*SD+I(time^3), random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML") #sleep deprivation explains variance in the slope of time (quadratic)
anova(model.6a,model.6d)

model.6e <-lme(reaction_time~time*SD+I(time^2)*SD+I(time^3)*SD, random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML") #sleep deprivation explains variance in the slope of time (quadratic)
anova(model.6a,model.6e) #sleep deprivation explains variance in the slope of time (cubic)

#best model
summary(model.6e)



```

#plotting the final model
```{r}
KSS_Complete_TIDY$SD <- as.factor(KSS_Complete_TIDY$SD)
RT.final.model <-lme(reaction_time~time*SD+I(time^2)*SD+I(time^3)*SD, random=~time+I(time^2)|ID, data=KSS_Complete_TIDY, na.action=na.omit, method="ML")

ggplot(KSS_Complete_TIDY, aes(time, reaction_time, colour=SD)) + 
  stat_summary(fun.data=mean_se, geom="pointrange") + 
  labs(y="Reaction Time (ms)", x="Time point") + 
  theme_bw() + scale_color_manual(values=c("red", "blue"))
last_plot() + stat_summary(aes(y=fitted(RT.final.model)), fun.y=mean, geom="line")

ggplot(KSS_Complete_TIDY, aes(time, reaction_time, colour=SD)) + 
  labs(y="Reaction Time (ms)", x="Time point") + 
  theme_bw() + stat_summary(aes(y=fitted(RT.final.model)), fun.y=mean, geom="point") + stat_smooth(method = "lm", formula  =y ~ poly(x,3))



http://www.danmirman.org/gca
https://biologyforfun.wordpress.com/2014/03/12/generalized-linear-mixed-models-in-ecology-and-in-r/
  http://stackoverflow.com/questions/20562795/plotting-proper-mixed-models-regression-slope
http://stackoverflow.com/questions/32196641/how-to-plot-predicted-values-with-standard-errors-for-lmer-model-results
http://brockferguson.com/tutorials/R-gca-workshop/tutorial4-growth-curve-analysis.html
http://www.eyetracking-r.com/vignettes/growth_curve_analysis
http://mindingthebrain.blogspot.se/2012/08/plotting-model-fits.html
```

