---
title: "Short-term Memory"
author: "Benjamin Holding"
date: 'Last Updated: `r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
} #function to see if package is installed. Will download if not, and then opens it.

packages <- c("data.table", "lubridate", "anytime", "dplyr", "ggplot2", "nlme", "tidyr", "lme4", "lmerTest", "sjPlot") #These are the extra packages needed to merge the CSV files
suppressPackageStartupMessages(ipak(packages))
```


```{r, include=FALSE}

myoriginalwd <- getwd()
setwd("Short-term memory") #enter the location of the data here between quotation marks
file_list <- list.files()
L <- length(file_list) 

STM_list <- lapply(file_list, read.csv, header=T, sep=",", dec=".")

setwd(myoriginalwd)
STM.names <- read.csv("STM_filenames.csv", header = F)

names(STM_list) <- STM.names[,1]

final.list <- mapply(cbind, STM_list, "SampleID"=STM.names[,1], SIMPLIFY=F)

WakeApp_STM <- rbindlist(final.list, fill = T) #this is the complete data frame
WakeApp_STM$id <- as.character(WakeApp_STM$id)
WakeApp_STM$id[which(WakeApp_STM$id == "SI_106_2")] <- "SI_106"
WakeApp_STM$id[which(WakeApp_STM$id == "SI_106_3")] <- "SI_106"
WakeApp_STM$id[which(WakeApp_STM$id == "SI_106_4")] <- "SI_106"

WakeApp_STM$id <- as.numeric(gsub("[^0-9]","",WakeApp_STM$id))
colnames(WakeApp_STM)[1] <- "ID"

slesi.key <- read.csv("SleSI_Masterkey.csv")

WakeApp_STM_complete <- inner_join(WakeApp_STM, slesi.key)

WakeApp_STM_complete$SampleID <- gsub("STM_", "", WakeApp_STM_complete$SampleID)
WakeApp_STM_complete$SampleID <- gsub(".csv", "", WakeApp_STM_complete$SampleID)

STM_Complete_TIDY <- WakeApp_STM_complete[c(-1,-2,-3)] %>% 
  separate(SampleID, into = c("ID", "time"), sep = "\\_")
                             
STM_Complete_TIDY$time <- as.integer(STM_Complete_TIDY$time)

data.check <- as.data.frame(unique(STM_Complete_TIDY[,c(12,15,16)]))
data.check$ID <- as.integer(data.check$ID)
data.check2 <- inner_join(data.check, slesi.key, by = "ID")
identical(data.check2$SD.x, data.check2$SD.y) #this checks that all the participants have the correct SD coding

#removing rows where word is > 24
STM_Complete_TIDY <- STM_Complete_TIDY[which(STM_Complete_TIDY$word < 25 ),]
```

#Analysis on overall score
```{r}
# assessing the best random intercepts
model.2a <- glmer(correct~1 + (1|ID), data=STM_Complete_TIDY, family=binomial)
model.2b <- glmer(correct~1 + (1|ID) + (1|word_pool),  data=STM_Complete_TIDY, family=binomial)
model.2c <- glmer(correct~1 + (1|ID) + (1|word),  data=STM_Complete_TIDY, family=binomial) #best
model.2d <- glmer(correct~1 + (1|ID) + (1|recall_session),  data=STM_Complete_TIDY, family=binomial)
model.2e <- glmer(correct~1 + (1|ID) + (1|recall_session) + (1|word),  data=STM_Complete_TIDY, family=binomial)

anova(model.2a, model.2b, model.2c, model.2d, model.2e) #best to include order of words as random effect

# assessing the best time polynomial
model.3a<-glmer(correct~1 + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial)
model.3b<-glmer(correct~time + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial)
model.3c<-glmer(correct~time + I(time^2) + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial)
model.3d<-glmer(correct~time + I(time^2) + I(time^3) + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial) #best

anova(model.3a, model.3b, model.3c,model.3d) #Cubic effect (model.3d) is best

#adding in sleep condition

model.6a<-glmer(correct~time + I(time^2) + I(time^3) + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial)
model.6b<-glmer(correct~time + I(time^2) + I(time^3) +SD + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial)
model.6c <-glmer(correct~time*SD + I(time^2) + I(time^3) + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial)
model.6d <- glmer(correct~time*SD + I(time^2)*SD + I(time^3) + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial)
model.6e <- glmer(correct~time*SD + I(time^2)*SD + I(time^3)*SD + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial) #best

anova(model.6a,model.6b, model.6c, model.6d, model.6e) #SD explains cubic effect of time

#adding in whether encoded or dummy word

model.7a <- glmer(correct~time*SD + I(time^2)*SD + I(time^3)*SD + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial) 
model.7b <- glmer(correct~endcoding + time*SD + I(time^2)*SD + I(time^3)*SD + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial) 
model.7c <- glmer(correct~endcoding*time*SD + I(time^2)*SD + I(time^3)*SD + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial) 
model.7d <- glmer(correct~endcoding*time*SD + endcoding*I(time^2)*SD + I(time^3)*SD + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial) 
model.7e <- glmer(correct~endcoding*time*SD + endcoding*I(time^2)*SD + endcoding*I(time^3)*SD + (1|ID) + (1|recall_session) + (1|word), data=STM_Complete_TIDY, family=binomial) 

anova(model.7a,model.7b,model.7c,model.7d,model.7e) 
```

#The best fitting model
```{r}
summary(model.7d)
```


#plotting the final model
```{r}
STM_Complete_TIDY$SD <- factor(STM_Complete_TIDY$SD, labels = c("Control", "Sleep Deprivation"))
STM_Complete_TIDY$endcoding <- factor(STM_Complete_TIDY$endcoding, labels = c("Dummy", "Encoded"))

STM.final.model <- model.7d

#raw data plot with 95% confidence intervals
ggplot(STM_Complete_TIDY, aes(time, correct, colour=SD)) + 
  stat_summary(fun.data=mean_cl_normal, fun.args=list(conf.int=0.95), geom="pointrange") + 
  labs(y="correct", x="Time point") +
  ggtitle("STM raw data plot with 95% confidence intervals") + 
  theme_bw() + scale_color_manual(values=c("red", "blue")) + stat_summary(fun.y=mean, geom="line") +
  facet_wrap( ~ endcoding)

ggplot(data = STM_Complete_TIDY,  aes(time, correct, colour=SD)) + 
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width =0.1) +
  stat_summary(fun.y=mean, geom="point")  +
  stat_summary(fun.y=mean, geom="line")  +
  stat_summary(fun.y = mean,geom = "point", size=4, aes(shape=SD,fill=SD)) + 
     scale_x_continuous("Time", breaks=0:3, labels = c("22:00", "09:00", "12:30", "16:00")) +
     scale_y_continuous("Percentage correct") +
     scale_shape_manual(values=c(24,21)) +
     scale_fill_manual(values=c("white","black")) +
  scale_color_manual(values=c('black','black')) + 
     theme_apa() +
  theme(axis.title = element_text(face = "bold"),
        panel.border = element_blank(),
        axis.line = element_line(color = 'black')) +
  facet_wrap( ~ endcoding)

#fitted model (aka predictive values) plot with 95% confidence intervals
ggplot(STM_Complete_TIDY, aes(time, correct, colour=SD)) + 
  labs(y="STM (correct score)", x="Time point") +
  ggtitle("STM model fitted (predicted) data plot with 95% confidence intervals") + 
  theme_bw() + stat_summary(aes(y=fitted(STM.final.model)), fun.data=mean_cl_normal, fun.args=list(conf.int=0.95), geom="pointrange") +
  stat_smooth(aes(y=fitted(STM.final.model)), method = "glm", formula = y ~ poly(x,3)) + 
  facet_wrap( ~ endcoding)

plot_model(STM.final.model, type = "pred", terms = c("time", "SD", "endcoding"))
```
